language: generic
sudo: required
services: 
    - docker

before_install:
    - docker build -t jovyn/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true jovyn/docker-react npm run test

